name: Build, Scan, Push to GCR, and Update Kustomize GitOps Repo

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  id-token: 'write'

jobs:
  build-scan-push-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID }}
          service_account: ${{ secrets.GCP_SA }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Set image vars
        run: |
          echo "IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/exercise-sec" >> $GITHUB_ENV
          echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$GIT_SHA ./app/sec-app # -t $IMAGE_NAME:latest
            
      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          version: latest

      - name: Scan Docker image
        run: |
          trivy image --exit-code 0 --severity HIGH,CRITICAL $IMAGE_NAME:$GIT_SHA

      - name: Push Docker image to GCR
        if: success()
        run: |
          # docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$GIT_SHA

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.ARGOCD_GITOPS_REPO }}
          token: ${{ secrets.ARGOCD_GITOPS_PAT }}
          path: gitops

      - name: Update Kustomize image tag
        run: |
          cd gitops
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          ./kustomize edit set image my-app=$IMAGE_NAME:$GIT_SHA
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update image to $IMAGE_NAME:$GIT_SHA"
          git push
